apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  type: NodePort
  selector:
    app: prime
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-deployment
  labels:
    app: prime
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        app: prime
    spec:
      containers:
      - name: prime
        image: prime:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "redis-service"
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

